updates

diff --git a/bin/npx b/bin/npx
--- a/bin/npx
+++ b/bin/npx
@@ -3,7 +3,7 @@
 set -euo pipefail
 
 if ! command -v docker >/dev/null 2>&1; then
-  echo "Cannot run 'php80', Docker not available" >&2
+  echo "Cannot run 'npx', Docker not available" >&2
   exit 1
 fi
 
@@ -20,10 +20,9 @@ docker run \
   --user $(id -u):$(id -g) \
   --cap-drop ALL \
   --read-only \
-  --mount type=tmpfs,destination=/tmp,tmpfs-mode=1770 \
-  --volume /etc/passwd:/etc/passwd:ro \
-  --volume /etc/group:/etc/group:ro \
+  --env HOME=/tmp \
+  --tmpfs /tmp \
   --volume "$(pwd)":/workdir \
   --workdir /workdir \
-  --entrypoint /usr/local/bin/php \
-  alcohol/php:8.0 "$@"
+  --entrypoint /usr/local/bin/npx \
+  node:current-alpine "$@"
diff --git a/bin/php82 b/bin/php82
--- a/bin/php82
+++ b/bin/php82
@@ -3,24 +3,27 @@
 set -euo pipefail
 
 if ! command -v docker >/dev/null 2>&1; then
-  echo "Cannot run 'popeye', Docker not available" >&2
+  echo "Cannot run 'php82', Docker not available" >&2
   exit 1
 fi
 
 tty=
 tty -s && tty=--tty
 
-[[ -d "$HOME/.kube" ]] || mkdir "$HOME/.kube"
-
 docker run \
   $tty \
   --interactive \
   --rm \
+  --pull=always \
+  --quiet \
+  --init \
   --user $(id -u):$(id -g) \
   --cap-drop ALL \
-  --env TERM=xterm-256color \
-  --tmpfs /tmp \
+  --read-only \
+  --mount type=tmpfs,destination=/tmp,tmpfs-mode=1770 \
   --volume /etc/passwd:/etc/passwd:ro \
   --volume /etc/group:/etc/group:ro \
-  --volume "$HOME/.kube":/home/rob/.kube \
-  derailed/popeye "$@"
+  --volume "$(pwd)":/workdir \
+  --workdir /workdir \
+  --entrypoint /usr/local/bin/php \
+  alcohol/php:8.2 "$@"
